### ISSUE TITLE
Fatal Error: Call to a member function getPath()

### ISSUE THREAD

**Issue by burpy** [Barzahlen/Barzahlen-PHP#14]
When I try the example code I get an Fatal Error: Call to a member function getPath() on null in /usr/share/php/vendor/barzahlen/barzahlen-php/src/Client.php on line 76

The code is:

```
<?php
require_once('vendor/autoload.php');

use Barzahlen\Client;
use Barzahlen\Exception\ApiException;

$client = new Client('12345', 'f2a173a210c7c8e7e439da7dc2b8330b6c06fc04', true);
$client->setUserAgent('Awesome Project v1.0.1');

try {
   $response = $client->handle($request);
   $stdClass = json_decode($response);
   $array = json_decode($response, true);
} catch (ApiException $e) {
   // @TODO: handle exception
}

```

Thanks for your help.

**Comment by martinseener** [comment]
Hi @burpy.
Thanks for trying out our SDK. Can you tell me some more information about your system where you tried to run it? Most importantly the PHP Version and maybe some other environmental informations like the OS and how you installed the SDK.

I'll then try to find your problem.

Cheers.

**Comment by burpy** [comment]
Hi @martinseener 

I run debian with PHP Version 5.6.29-0+deb8u1. I installed it with composer.

Thanks!

**Comment by martinseener** [comment]
Hi @burpy 
my fault. Should have seen this earlier. The problem is, that the code you use is only an example on how you can initiate the client. You try to create a response (first line in the try: block) with a non-existent `$request`.

First, read through the README. A bit below this code you see the Requests that can be made. So at first you have to build the `$request` and then call `$client->handle(...)`.

I hope i could help you.
